title: "Open Innovation City Bielefeld"
description: "Offene Innovationen für eine lebenswerte Stadt."
url: ""  # beim Deploy aktualisieren
baseurl: ""  # z.B. /oic
language: "de"
collections:
  news:
    output: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap